server:
  port: 2000

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/product_shop_springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
